[tool.poetry]
name = "rag"
version = "0.1.0"
description = "RAG Demo"
authors = ["Kazuki Kijima <kazukiyoshida96@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
chromadb = "0.5.5"
openai = "1.44.0"
fastapi = {extras = ["standard"], version = "0.114.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
